spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vcg?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    ROOT: info
    com.lzj.vcg: debug
